### ISSUE TITLE
Unable to install on 0.7.8

### ISSUE THREAD

**Issue by DarKDinDoN** [janssen-io/foundry-macro-marker#11]
![image](https://user-images.githubusercontent.com/1687854/101980171-d94c0980-3c63-11eb-9862-bb0c880690b9.png)

**Comment by MrVauxs** [comment]
Also happens in [Token Hotbar](https://github.com/janssen-io/foundry-token-hotbar/issues/36)

**Comment by janssen-io** [comment]
Thanks for the report! I have resolved the issue and you should be able to download the package again.

The reason I'm using another address that github directly is for statistics and control over new changes. Especially when a new major version is released, it is nice to release it slowly to new users rather than everyone at once.

I will probably reconsider this in 2021 as development on the modules also has slowed down.

Sorry for any inconvenience!
